/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    categories: Category;
    orders: Order;
    customers: Customer;
    coupons: Coupon;
    'shipping-zones': ShippingZone;
    guestbook: Guestbook;
    fanarts: Fanart;
    polls: Poll;
    'poll-votes': PollVote;
    announcements: Announcement;
    downloads: Download;
    'protected-files': ProtectedFile;
    'surprise-codes': SurpriseCode;
    'notify-signups': NotifySignup;
    members: Member;
    scores: Score;
    'game-sessions': GameSession;
    games: Game;
    'game-assets': GameAsset;
    'legal-pages': LegalPage;
    'schedule-archive': ScheduleArchive;
    'activity-log': ActivityLog;
    'webhook-events': WebhookEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'shipping-zones': ShippingZonesSelect<false> | ShippingZonesSelect<true>;
    guestbook: GuestbookSelect<false> | GuestbookSelect<true>;
    fanarts: FanartsSelect<false> | FanartsSelect<true>;
    polls: PollsSelect<false> | PollsSelect<true>;
    'poll-votes': PollVotesSelect<false> | PollVotesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    'protected-files': ProtectedFilesSelect<false> | ProtectedFilesSelect<true>;
    'surprise-codes': SurpriseCodesSelect<false> | SurpriseCodesSelect<true>;
    'notify-signups': NotifySignupsSelect<false> | NotifySignupsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    scores: ScoresSelect<false> | ScoresSelect<true>;
    'game-sessions': GameSessionsSelect<false> | GameSessionsSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    'game-assets': GameAssetsSelect<false> | GameAssetsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'schedule-archive': ScheduleArchiveSelect<false> | ScheduleArchiveSelect<true>;
    'activity-log': ActivityLogSelect<false> | ActivityLogSelect<true>;
    'webhook-events': WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    theme: Theme;
    'home-page': HomePage;
    'biography-page': BiographyPage;
    'links-page': LinksPage;
    schedule: Schedule;
    'shop-settings': ShopSetting;
    'easter-eggs': EasterEgg;
    'game-settings': GameSetting;
    'moderation-settings': ModerationSetting;
    'legal-identity': LegalIdentity;
    integrations: Integration;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'biography-page': BiographyPageSelect<false> | BiographyPageSelect<true>;
    'links-page': LinksPageSelect<false> | LinksPageSelect<true>;
    schedule: ScheduleSelect<false> | ScheduleSelect<true>;
    'shop-settings': ShopSettingsSelect<false> | ShopSettingsSelect<true>;
    'easter-eggs': EasterEggsSelect<false> | EasterEggsSelect<true>;
    'game-settings': GameSettingsSelect<false> | GameSettingsSelect<true>;
    'moderation-settings': ModerationSettingsSelect<false> | ModerationSettingsSelect<true>;
    'legal-identity': LegalIdentitySelect<false> | LegalIdentitySelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('admin' | 'editor' | 'moderator')[];
  totpEnabled?: boolean | null;
  totpEnabledAt?: string | null;
  totpSecret?: string | null;
  totpPendingSecret?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug?: string | null;
  categories?: (number | Category)[] | null;
  fulfillment: 'gelato' | 'stock';
  badge?: string | null;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  price: number;
  compareAtPrice?: number | null;
  vatKey?: string | null;
  personalized?: boolean | null;
  /**
   * Au moins une variante (ex. « Unique » pour un produit sans taille). Le SKU doit être unique.
   */
  variants?:
    | {
        label: string;
        sku: string;
        size?: string | null;
        color?: string | null;
        price?: number | null;
        stock?: number | null;
        gelatoProductUid?: string | null;
        gelatoFileUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  number: string;
  status:
    | 'pending'
    | 'paid'
    | 'in_production'
    | 'shipped'
    | 'delivered'
    | 'cancelled'
    | 'refunded'
    | 'partially_refunded'
    | 'failed';
  testMode?: boolean | null;
  email: string;
  customer?: (number | null) | Customer;
  provider: 'stripe' | 'paypal';
  providerRef?: string | null;
  paymentId?: string | null;
  items?:
    | {
        title?: string | null;
        variantLabel?: string | null;
        sku?: string | null;
        quantity?: number | null;
        unitPrice?: number | null;
        discount?: number | null;
        vatRate?: number | null;
        fulfillment?: string | null;
        product?: (number | null) | Product;
        gelatoProductUid?: string | null;
        gelatoFileUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  amounts?: {
    subtotal?: number | null;
    discount?: number | null;
    shipping?: number | null;
    vat?: number | null;
    vatBreakdown?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  total?: number | null;
  coupon?: (number | null) | Coupon;
  couponCode?: string | null;
  shippingZone?: (number | null) | ShippingZone;
  shippingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    line1?: string | null;
    line2?: string | null;
    postalCode?: string | null;
    city?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  fulfillment?: {
    gelatoOrderId?: string | null;
    gelatoStatus?: string | null;
    gelatoError?: string | null;
    carrier?: string | null;
    trackingNumber?: string | null;
    trackingUrl?: string | null;
  };
  refunds?:
    | {
        amount?: number | null;
        reference?: string | null;
        at?: string | null;
        by?: string | null;
        id?: string | null;
      }[]
    | null;
  invoiceNumber?: string | null;
  paidAt?: string | null;
  accessToken?: string | null;
  emailsSent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  email: string;
  name?: string | null;
  phone?: string | null;
  ordersCount?: number | null;
  totalSpent?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  active?: boolean | null;
  batch?: string | null;
  type: 'percent' | 'fixed' | 'freeShipping';
  value?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  maxUses?: number | null;
  maxUsesPerCustomer?: number | null;
  minAmount?: number | null;
  products?: (number | Product)[] | null;
  categories?: (number | Category)[] | null;
  note?: string | null;
  usageCount?: number | null;
  revenue?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-zones".
 */
export interface ShippingZone {
  id: number;
  name: string;
  countries: string;
  base: number;
  perExtraItem?: number | null;
  freeFrom?: number | null;
  delay?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Astuce : la file « 🛡️ Modération » (menu de gauche) permet de valider plus vite, avec aperçu et alertes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guestbook".
 */
export interface Guestbook {
  id: number;
  status: 'pending' | 'approved' | 'rejected';
  rejectionReason?: string | null;
  flags?: ('insult' | 'vulgar' | 'link' | 'personal' | 'spam' | 'caps' | 'custom' | 'duplicate')[] | null;
  flaggedTerms?: string | null;
  moderatedBy?: (number | null) | User;
  moderatedAt?: string | null;
  name: string;
  message: string;
  mood?: ('star' | 'heart' | 'fish' | 'bubble' | 'music') | null;
  reply?: string | null;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Astuce : la file « 🛡️ Modération » (menu de gauche) permet de valider plus vite, avec aperçu et alertes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fanarts".
 */
export interface Fanart {
  id: number;
  status: 'pending' | 'approved' | 'rejected';
  rejectionReason?: string | null;
  flags?: ('insult' | 'vulgar' | 'link' | 'personal' | 'spam' | 'caps' | 'custom' | 'duplicate')[] | null;
  flaggedTerms?: string | null;
  moderatedBy?: (number | null) | User;
  moderatedAt?: string | null;
  fileHash?: string | null;
  title: string;
  artist: string;
  artistLink?: string | null;
  licenseAccepted: boolean;
  contactEmail?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    preview?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls".
 */
export interface Poll {
  id: number;
  question: string;
  active?: boolean | null;
  closesAt?: string | null;
  options?:
    | {
        label: string;
        votes?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-votes".
 */
export interface PollVote {
  id: number;
  poll: number | Poll;
  voterHash: string;
  option: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pinned?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: number;
  title: string;
  kind: 'wallpaper' | 'widget' | 'emojis' | 'other';
  preview: number | Media;
  files?:
    | {
        format: 'phone' | 'tablet' | 'desktop' | 'zip';
        file: number | ProtectedFile;
        id?: string | null;
      }[]
    | null;
  locked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "protected-files".
 */
export interface ProtectedFile {
  id: number;
  label?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surprise-codes".
 */
export interface SurpriseCode {
  id: number;
  code: string;
  source?: ('live' | 'easterEgg' | 'game' | 'other') | null;
  unlocks?: (number | Download)[] | null;
  message?: string | null;
  active?: boolean | null;
  expiresAt?: string | null;
  redemptions?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notify-signups".
 */
export interface NotifySignup {
  id: number;
  email: string;
  section: string;
  consentAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  twitchId: string;
  displayName: string;
  avatarUrl?: string | null;
  banned?: boolean | null;
  unlockedCodes?: (number | SurpriseCode)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores".
 */
export interface Score {
  id: number;
  game: string;
  nickname: string;
  score: number;
  floor: number;
  won?: boolean | null;
  durationMs?: number | null;
  seed?: string | null;
  daily?: boolean | null;
  hidden?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-sessions".
 */
export interface GameSession {
  id: number;
  game: string;
  seed: string;
  daily?: boolean | null;
  startedAt: string;
  used?: boolean | null;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Chaque jeu apparaît comme une borne sur /arcade. « Moteur intégré » = The Ratsu (réglages détaillés dans Réglages The Ratsu). « Code personnalisé » = ta propre page HTML/JS, injectée dans une iframe isolée.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: number;
  title: string;
  slug?: string | null;
  status: 'live' | 'soon' | 'off';
  order?: number | null;
  tagline?: string | null;
  color?: string | null;
  thumbnail?: (number | null) | Media;
  engine: 'ratsu' | 'custom';
  /**
   * Page HTML autonome (balises <style>/<script> incluses). Rendue dans une iframe isolée : pas d’accès aux cookies ni aux données du site. Astuce : utilise window.parent.postMessage({type:'liratsu:score', score}, '*') si tu veux qu’on affiche le score (classement non certifié pour les jeux personnalisés).
   */
  code?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-assets".
 */
export interface GameAsset {
  id: number;
  label: string;
  kind: 'sprite' | 'music';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Pages juridiques gérées par Reads Records. Chaque enregistrement crée une version consultable.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  slug: 'mentions-legales' | 'cgu' | 'cgv' | 'confidentialite' | 'cookies';
  lastUpdated?: string | null;
  keepDate?: boolean | null;
  showIdentity?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-archive".
 */
export interface ScheduleArchive {
  id: number;
  date: string;
  title: string;
  game?: string | null;
  boxArtUrl?: string | null;
  kind?: ('game' | 'art' | 'music' | 'chat') | null;
  vodUrl?: string | null;
  vodFound?: boolean | null;
  vodTitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log".
 */
export interface ActivityLog {
  id: number;
  summary: string;
  user?: (number | null) | User;
  entity?: string | null;
  entityId?: string | null;
  operation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events".
 */
export interface WebhookEvent {
  id: number;
  eventId: string;
  source: string;
  type?: string | null;
  order?: (number | null) | Order;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'shipping-zones';
        value: number | ShippingZone;
      } | null)
    | ({
        relationTo: 'guestbook';
        value: number | Guestbook;
      } | null)
    | ({
        relationTo: 'fanarts';
        value: number | Fanart;
      } | null)
    | ({
        relationTo: 'polls';
        value: number | Poll;
      } | null)
    | ({
        relationTo: 'poll-votes';
        value: number | PollVote;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'downloads';
        value: number | Download;
      } | null)
    | ({
        relationTo: 'protected-files';
        value: number | ProtectedFile;
      } | null)
    | ({
        relationTo: 'surprise-codes';
        value: number | SurpriseCode;
      } | null)
    | ({
        relationTo: 'notify-signups';
        value: number | NotifySignup;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'scores';
        value: number | Score;
      } | null)
    | ({
        relationTo: 'game-sessions';
        value: number | GameSession;
      } | null)
    | ({
        relationTo: 'games';
        value: number | Game;
      } | null)
    | ({
        relationTo: 'game-assets';
        value: number | GameAsset;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'schedule-archive';
        value: number | ScheduleArchive;
      } | null)
    | ({
        relationTo: 'activity-log';
        value: number | ActivityLog;
      } | null)
    | ({
        relationTo: 'webhook-events';
        value: number | WebhookEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  totpEnabled?: T;
  totpEnabledAt?: T;
  totpSecret?: T;
  totpPendingSecret?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  categories?: T;
  fulfillment?: T;
  badge?: T;
  shortDescription?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  price?: T;
  compareAtPrice?: T;
  vatKey?: T;
  personalized?: T;
  variants?:
    | T
    | {
        label?: T;
        sku?: T;
        size?: T;
        color?: T;
        price?: T;
        stock?: T;
        gelatoProductUid?: T;
        gelatoFileUrl?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  status?: T;
  testMode?: T;
  email?: T;
  customer?: T;
  provider?: T;
  providerRef?: T;
  paymentId?: T;
  items?:
    | T
    | {
        title?: T;
        variantLabel?: T;
        sku?: T;
        quantity?: T;
        unitPrice?: T;
        discount?: T;
        vatRate?: T;
        fulfillment?: T;
        product?: T;
        gelatoProductUid?: T;
        gelatoFileUrl?: T;
        id?: T;
      };
  amounts?:
    | T
    | {
        subtotal?: T;
        discount?: T;
        shipping?: T;
        vat?: T;
        vatBreakdown?: T;
      };
  total?: T;
  coupon?: T;
  couponCode?: T;
  shippingZone?: T;
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        line1?: T;
        line2?: T;
        postalCode?: T;
        city?: T;
        country?: T;
        phone?: T;
      };
  fulfillment?:
    | T
    | {
        gelatoOrderId?: T;
        gelatoStatus?: T;
        gelatoError?: T;
        carrier?: T;
        trackingNumber?: T;
        trackingUrl?: T;
      };
  refunds?:
    | T
    | {
        amount?: T;
        reference?: T;
        at?: T;
        by?: T;
        id?: T;
      };
  invoiceNumber?: T;
  paidAt?: T;
  accessToken?: T;
  emailsSent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  phone?: T;
  ordersCount?: T;
  totalSpent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  active?: T;
  batch?: T;
  type?: T;
  value?: T;
  startsAt?: T;
  endsAt?: T;
  maxUses?: T;
  maxUsesPerCustomer?: T;
  minAmount?: T;
  products?: T;
  categories?: T;
  note?: T;
  usageCount?: T;
  revenue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-zones_select".
 */
export interface ShippingZonesSelect<T extends boolean = true> {
  name?: T;
  countries?: T;
  base?: T;
  perExtraItem?: T;
  freeFrom?: T;
  delay?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guestbook_select".
 */
export interface GuestbookSelect<T extends boolean = true> {
  status?: T;
  rejectionReason?: T;
  flags?: T;
  flaggedTerms?: T;
  moderatedBy?: T;
  moderatedAt?: T;
  name?: T;
  message?: T;
  mood?: T;
  reply?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fanarts_select".
 */
export interface FanartsSelect<T extends boolean = true> {
  status?: T;
  rejectionReason?: T;
  flags?: T;
  flaggedTerms?: T;
  moderatedBy?: T;
  moderatedAt?: T;
  fileHash?: T;
  title?: T;
  artist?: T;
  artistLink?: T;
  licenseAccepted?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        preview?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls_select".
 */
export interface PollsSelect<T extends boolean = true> {
  question?: T;
  active?: T;
  closesAt?: T;
  options?:
    | T
    | {
        label?: T;
        votes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-votes_select".
 */
export interface PollVotesSelect<T extends boolean = true> {
  poll?: T;
  voterHash?: T;
  option?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  pinned?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  preview?: T;
  files?:
    | T
    | {
        format?: T;
        file?: T;
        id?: T;
      };
  locked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "protected-files_select".
 */
export interface ProtectedFilesSelect<T extends boolean = true> {
  label?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surprise-codes_select".
 */
export interface SurpriseCodesSelect<T extends boolean = true> {
  code?: T;
  source?: T;
  unlocks?: T;
  message?: T;
  active?: T;
  expiresAt?: T;
  redemptions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notify-signups_select".
 */
export interface NotifySignupsSelect<T extends boolean = true> {
  email?: T;
  section?: T;
  consentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  twitchId?: T;
  displayName?: T;
  avatarUrl?: T;
  banned?: T;
  unlockedCodes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores_select".
 */
export interface ScoresSelect<T extends boolean = true> {
  game?: T;
  nickname?: T;
  score?: T;
  floor?: T;
  won?: T;
  durationMs?: T;
  seed?: T;
  daily?: T;
  hidden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-sessions_select".
 */
export interface GameSessionsSelect<T extends boolean = true> {
  game?: T;
  seed?: T;
  daily?: T;
  startedAt?: T;
  used?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  order?: T;
  tagline?: T;
  color?: T;
  thumbnail?: T;
  engine?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-assets_select".
 */
export interface GameAssetsSelect<T extends boolean = true> {
  label?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lastUpdated?: T;
  keepDate?: T;
  showIdentity?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-archive_select".
 */
export interface ScheduleArchiveSelect<T extends boolean = true> {
  date?: T;
  title?: T;
  game?: T;
  boxArtUrl?: T;
  kind?: T;
  vodUrl?: T;
  vodFound?: T;
  vodTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log_select".
 */
export interface ActivityLogSelect<T extends boolean = true> {
  summary?: T;
  user?: T;
  entity?: T;
  entityId?: T;
  operation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  eventId?: T;
  source?: T;
  type?: T;
  order?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteUrl: string;
  tagline?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  avatar?: (number | null) | Media;
  twitch?: string | null;
  /**
   * URL de la chaîne YouTube (à renseigner).
   */
  youtube?: string | null;
  instagram?: string | null;
  tiktok?: string | null;
  discord?: string | null;
  home: {
    status: 'on' | 'off' | 'soon';
    showInMenu?: boolean | null;
    menuLabel?: string | null;
    teaserText?: string | null;
    notifyForm?: boolean | null;
  };
  biography: {
    status: 'on' | 'off' | 'soon';
    showInMenu?: boolean | null;
    menuLabel?: string | null;
    teaserText?: string | null;
    notifyForm?: boolean | null;
  };
  community: {
    status: 'on' | 'off' | 'soon';
    showInMenu?: boolean | null;
    menuLabel?: string | null;
    teaserText?: string | null;
    notifyForm?: boolean | null;
  };
  shop: {
    status: 'on' | 'off' | 'soon';
    showInMenu?: boolean | null;
    menuLabel?: string | null;
    teaserText?: string | null;
    notifyForm?: boolean | null;
  };
  arcade: {
    status: 'on' | 'off' | 'soon';
    showInMenu?: boolean | null;
    menuLabel?: string | null;
    teaserText?: string | null;
    notifyForm?: boolean | null;
  };
  links: {
    status: 'on' | 'off' | 'soon';
    showInMenu?: boolean | null;
    menuLabel?: string | null;
    teaserText?: string | null;
    notifyForm?: boolean | null;
  };
  footerText?: string | null;
  devCredit?: string | null;
  publisherCredit?: string | null;
  maintenanceMode?: boolean | null;
  maintenanceMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  palette?: {
    aero?: string | null;
    deep?: string | null;
    lagoon?: string | null;
    candy?: string | null;
    lime?: string | null;
    star?: string | null;
    ink?: string | null;
    cloud?: string | null;
  };
  /**
   * Les visiteurs peuvent aussi couper animations et sons ; prefers-reduced-motion est toujours respecté.
   */
  effects?: {
    bubbles?: boolean | null;
    fish?: boolean | null;
    soundsAvailable?: boolean | null;
    customCursors?: boolean | null;
    defaultMode?: ('auto' | 'light' | 'dark') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  layout?:
    | (
        | {
            tagline?: string | null;
            intro?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            showAvatar?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            showPlayer?: boolean | null;
            offlineText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'liveStatus';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            /**
             * Le contenu du planning se gère dans Réglages > Planning (dates réelles) — ce bloc choisit juste où l’afficher sur la page.
             */
            source?: ('auto' | 'manual') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'schedule';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            count?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'clips';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            count?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'youtube';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            posts?:
              | {
                  network: 'instagram' | 'tiktok';
                  url: string;
                  thumbnail: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'socialPosts';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'socialGrid';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            label: string;
            current: number;
            target: number;
            reward?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'communityGoal';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            plain?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            style?: ('polaroid' | 'window' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biography-page".
 */
export interface BiographyPage {
  id: number;
  title?: string | null;
  intro?: string | null;
  layout?:
    | (
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            plain?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            style?: ('polaroid' | 'window' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            events?:
              | {
                  date: string;
                  icon?: ('star' | 'bubble' | 'heart' | 'pencil' | 'note' | 'gamepad' | 'fish') | null;
                  title: string;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            displayName?: string | null;
            mood?: string | null;
            presence?: ('online' | 'busy' | 'away') | null;
            avatar?: (number | null) | Media;
            facts?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'profileCard';
          }
        | {
            /**
             * Texte de la barre de titre façon fenêtre aero (optionnel).
             */
            windowTitle?: string | null;
            label: string;
            current: number;
            target: number;
            reward?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'communityGoal';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links-page".
 */
export interface LinksPage {
  id: number;
  title?: string | null;
  subtitle?: string | null;
  links?:
    | {
        label: string;
        url: string;
        icon?:
          | (
              | 'twitch'
              | 'youtube'
              | 'instagram'
              | 'tiktok'
              | 'discord'
              | 'shop'
              | 'star'
              | 'bubble'
              | 'heart'
              | 'gamepad'
              | 'mail'
            )
          | null;
        color?: ('aero' | 'lagoon' | 'candy' | 'lime' | 'star' | 'deep') | null;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Les prochains streams, avec une vraie date (pas juste un jour de la semaine). Un créneau retiré de cette liste une fois sa date passée part automatiquement dans « Anciens plannings ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule".
 */
export interface Schedule {
  id: number;
  /**
   * Trié automatiquement par date (le plus proche en premier) sur le site.
   */
  items?:
    | {
        date: string;
        time: string;
        kind?: ('game' | 'art' | 'music' | 'chat') | null;
        title: string;
        /**
         * Cherche n’importe quelle catégorie Twitch : un jeu, mais aussi « Just Chatting », « Art », « Music »… Laisse vide pour garder une simple icône.
         */
        game?: string | null;
        boxArtUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings".
 */
export interface ShopSetting {
  id: number;
  testMode?: boolean | null;
  currency?: 'EUR' | null;
  /**
   * Les prix saisis sont TTC ; la TVA est extraite pour les factures.
   */
  vatRates?:
    | {
        key: string;
        label: string;
        rate: number;
        id?: string | null;
      }[]
    | null;
  enabledPayments?: ('stripe' | 'paypal')[] | null;
  /**
   * Informations de l’émetteur des factures (Reads Records). À compléter/vérifier.
   */
  invoice?: {
    issuerName?: string | null;
    issuerDetails?: string | null;
    prefix?: string | null;
    footer?: string | null;
  };
  freeShippingThreshold?: number | null;
  checkoutNotice?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "easter-eggs".
 */
export interface EasterEgg {
  id: number;
  konami?: boolean | null;
  logoPop?: boolean | null;
  windowClose?: boolean | null;
  wizz?: boolean | null;
  footerCredit?: boolean | null;
  console?: boolean | null;
  aquarium404?: boolean | null;
  secretCode?: boolean | null;
  secretHint?: ('fishClicks' | 'typeGlouglou') | null;
  /**
   * Code donné au visiteur qui trouve l’easter egg secret.
   */
  secretReward?: (number | null) | SurpriseCode;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-settings".
 */
export interface GameSetting {
  id: number;
  ratsu?: {
    enabled?: boolean | null;
    leaderboardEnabled?: boolean | null;
    difficulty?: ('easy' | 'normal' | 'hard') | null;
    startHearts?: number | null;
    floors?: number | null;
    maxScorePerSecond?: number | null;
    /**
     * Défis qui débloquent un code surprise (fond d’écran, pack…) dans l’Espace communauté.
     */
    unlocks?:
      | {
          condition: 'floor' | 'score' | 'win' | 'daily';
          threshold?: number | null;
          reward: number | SurpriseCode;
          message?: string | null;
          id?: string | null;
        }[]
      | null;
    spriteOverrides?:
      | {
          key:
            | 'player'
            | 'floorTile'
            | 'wallTile'
            | 'rockTile'
            | 'pickupCoin'
            | 'pickupHeart'
            | 'enemyGoldfish'
            | 'enemyBubble'
            | 'enemyPopup'
            | 'enemyCursor'
            | 'enemyLag'
            | 'enemyTroll'
            | 'bossPopup'
            | 'bossSun';
          image: number | GameAsset;
          id?: string | null;
        }[]
      | null;
    /**
     * Jouées en boucle pendant la partie (coupées par défaut, un bouton 🎵 permet de les activer). Sans piste : silence.
     */
    musicTracks?:
      | {
          title: string;
          file: number | GameAsset;
          /**
           * 1 = dès le début. Utilisé pour changer de piste en montant d’étage.
           */
          floorFrom?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Le filtre automatique bloque ou signale les messages ; les modérateurs valident ensuite dans « Modération ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-settings".
 */
export interface ModerationSetting {
  id: number;
  links?: ('block' | 'review' | 'allow') | null;
  allowedDomains?: string | null;
  blockPersonal?: boolean | null;
  /**
   * Un par ligne. Les variantes (majuscules, accents, l33t « s4l0p3 », lettres espacées) sont détectées automatiquement.
   */
  blockedWords?: string | null;
  /**
   * Un par ligne. Pratique pour les spoilers, les pseudos de trolls connus, etc.
   */
  watchedWords?: string | null;
  /**
   * Désactivé par défaut : tous les messages passent par un modérateur (modération a priori).
   */
  autoApproveClean?: boolean | null;
  rejectDuplicates?: boolean | null;
  emailArtist?: boolean | null;
  rejectionReasons?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  notify?: boolean | null;
  /**
   * Vide = adresse « Email de notification interne » des réglages SMTP.
   */
  notifyEmails?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * À reprendre à l’identique depuis reads-records.com. Utilisable dans les textes via {{editeur.nom}}, {{editeur.siren}}, {{hebergeur.nom}}, etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-identity".
 */
export interface LegalIdentity {
  id: number;
  editeur?: {
    nom?: string | null;
    forme?: string | null;
    capital?: string | null;
    siege?: string | null;
    rcs?: string | null;
    siren?: string | null;
    tva?: string | null;
    directeur?: string | null;
    email?: string | null;
    telephone?: string | null;
    site?: string | null;
  };
  /**
   * IONOS : coordonnées à vérifier sur ionos.fr avant mise en ligne.
   */
  hebergeur?: {
    nom?: string | null;
    adresse?: string | null;
    telephone?: string | null;
    site?: string | null;
  };
  mediateur?: {
    nom?: string | null;
    site?: string | null;
  };
  dpoEmail?: string | null;
  developpeur?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Réservé aux admins. Les secrets ne sont jamais réaffichés en clair.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  twitch?: {
    channelLogin?: string | null;
    clientId?: string | null;
    /**
     * Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
     */
    clientSecret?: string | null;
    oauthEnabled?: boolean | null;
  };
  youtube?: {
    /**
     * Utilisé pour le flux RSS public : aucune clé API nécessaire.
     */
    channelId?: string | null;
    /**
     * Sans le « @ ». Utilisé pour retrouver automatiquement le lien de VOD d’un ancien planning.
     */
    vodChannelHandle?: string | null;
  };
  stripe?: {
    test?: {
      publishableKey?: string | null;
      /**
       * Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
       */
      secretKey?: string | null;
      /**
       * Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
       */
      webhookSecret?: string | null;
    };
    live?: {
      publishableKey?: string | null;
      /**
       * Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
       */
      secretKey?: string | null;
      /**
       * Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
       */
      webhookSecret?: string | null;
    };
  };
  paypal?: {
    sandbox?: {
      clientId?: string | null;
      /**
       * Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
       */
      clientSecret?: string | null;
      webhookId?: string | null;
    };
    live?: {
      clientId?: string | null;
      /**
       * Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
       */
      clientSecret?: string | null;
      webhookId?: string | null;
    };
  };
  gelato?: {
    /**
     * Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
     */
    apiKey?: string | null;
    /**
     * Chaîne aléatoire ajoutée à l’URL du webhook (?token=…) — Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
     */
    webhookToken?: string | null;
  };
  smtp?: {
    host?: string | null;
    port?: number | null;
    secure?: boolean | null;
    user?: string | null;
    /**
     * Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
     */
    password?: string | null;
    from?: string | null;
    adminNotify?: string | null;
  };
  discord?: {
    /**
     * Discord : Paramètres du salon > Intégrations > Webhooks > Nouveau webhook > Copier l’URL — Stocké chiffré, jamais affiché en clair. Laisser le masque pour conserver la valeur.
     */
    scheduleWebhookUrl?: string | null;
  };
  analytics?: {
    provider?: ('none' | 'umami' | 'plausible') | null;
    scriptUrl?: string | null;
    siteId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  tagline?: T;
  metaDescription?: T;
  ogImage?: T;
  avatar?: T;
  twitch?: T;
  youtube?: T;
  instagram?: T;
  tiktok?: T;
  discord?: T;
  home?:
    | T
    | {
        status?: T;
        showInMenu?: T;
        menuLabel?: T;
        teaserText?: T;
        notifyForm?: T;
      };
  biography?:
    | T
    | {
        status?: T;
        showInMenu?: T;
        menuLabel?: T;
        teaserText?: T;
        notifyForm?: T;
      };
  community?:
    | T
    | {
        status?: T;
        showInMenu?: T;
        menuLabel?: T;
        teaserText?: T;
        notifyForm?: T;
      };
  shop?:
    | T
    | {
        status?: T;
        showInMenu?: T;
        menuLabel?: T;
        teaserText?: T;
        notifyForm?: T;
      };
  arcade?:
    | T
    | {
        status?: T;
        showInMenu?: T;
        menuLabel?: T;
        teaserText?: T;
        notifyForm?: T;
      };
  links?:
    | T
    | {
        status?: T;
        showInMenu?: T;
        menuLabel?: T;
        teaserText?: T;
        notifyForm?: T;
      };
  footerText?: T;
  devCredit?: T;
  publisherCredit?: T;
  maintenanceMode?: T;
  maintenanceMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  palette?:
    | T
    | {
        aero?: T;
        deep?: T;
        lagoon?: T;
        candy?: T;
        lime?: T;
        star?: T;
        ink?: T;
        cloud?: T;
      };
  effects?:
    | T
    | {
        bubbles?: T;
        fish?: T;
        soundsAvailable?: T;
        customCursors?: T;
        defaultMode?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              tagline?: T;
              intro?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              showAvatar?: T;
              id?: T;
              blockName?: T;
            };
        liveStatus?:
          | T
          | {
              windowTitle?: T;
              showPlayer?: T;
              offlineText?: T;
              id?: T;
              blockName?: T;
            };
        schedule?:
          | T
          | {
              windowTitle?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
        clips?:
          | T
          | {
              windowTitle?: T;
              count?: T;
              id?: T;
              blockName?: T;
            };
        youtube?:
          | T
          | {
              windowTitle?: T;
              count?: T;
              id?: T;
              blockName?: T;
            };
        socialPosts?:
          | T
          | {
              windowTitle?: T;
              posts?:
                | T
                | {
                    network?: T;
                    url?: T;
                    thumbnail?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        socialGrid?:
          | T
          | {
              windowTitle?: T;
              id?: T;
              blockName?: T;
            };
        communityGoal?:
          | T
          | {
              windowTitle?: T;
              label?: T;
              current?: T;
              target?: T;
              reward?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              windowTitle?: T;
              content?: T;
              plain?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biography-page_select".
 */
export interface BiographyPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              windowTitle?: T;
              content?: T;
              plain?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              windowTitle?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              windowTitle?: T;
              events?:
                | T
                | {
                    date?: T;
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        profileCard?:
          | T
          | {
              windowTitle?: T;
              displayName?: T;
              mood?: T;
              presence?: T;
              avatar?: T;
              facts?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        communityGoal?:
          | T
          | {
              windowTitle?: T;
              label?: T;
              current?: T;
              target?: T;
              reward?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links-page_select".
 */
export interface LinksPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        icon?: T;
        color?: T;
        highlight?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule_select".
 */
export interface ScheduleSelect<T extends boolean = true> {
  items?:
    | T
    | {
        date?: T;
        time?: T;
        kind?: T;
        title?: T;
        game?: T;
        boxArtUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings_select".
 */
export interface ShopSettingsSelect<T extends boolean = true> {
  testMode?: T;
  currency?: T;
  vatRates?:
    | T
    | {
        key?: T;
        label?: T;
        rate?: T;
        id?: T;
      };
  enabledPayments?: T;
  invoice?:
    | T
    | {
        issuerName?: T;
        issuerDetails?: T;
        prefix?: T;
        footer?: T;
      };
  freeShippingThreshold?: T;
  checkoutNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "easter-eggs_select".
 */
export interface EasterEggsSelect<T extends boolean = true> {
  konami?: T;
  logoPop?: T;
  windowClose?: T;
  wizz?: T;
  footerCredit?: T;
  console?: T;
  aquarium404?: T;
  secretCode?: T;
  secretHint?: T;
  secretReward?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-settings_select".
 */
export interface GameSettingsSelect<T extends boolean = true> {
  ratsu?:
    | T
    | {
        enabled?: T;
        leaderboardEnabled?: T;
        difficulty?: T;
        startHearts?: T;
        floors?: T;
        maxScorePerSecond?: T;
        unlocks?:
          | T
          | {
              condition?: T;
              threshold?: T;
              reward?: T;
              message?: T;
              id?: T;
            };
        spriteOverrides?:
          | T
          | {
              key?: T;
              image?: T;
              id?: T;
            };
        musicTracks?:
          | T
          | {
              title?: T;
              file?: T;
              floorFrom?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-settings_select".
 */
export interface ModerationSettingsSelect<T extends boolean = true> {
  links?: T;
  allowedDomains?: T;
  blockPersonal?: T;
  blockedWords?: T;
  watchedWords?: T;
  autoApproveClean?: T;
  rejectDuplicates?: T;
  emailArtist?: T;
  rejectionReasons?:
    | T
    | {
        label?: T;
        id?: T;
      };
  notify?: T;
  notifyEmails?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-identity_select".
 */
export interface LegalIdentitySelect<T extends boolean = true> {
  editeur?:
    | T
    | {
        nom?: T;
        forme?: T;
        capital?: T;
        siege?: T;
        rcs?: T;
        siren?: T;
        tva?: T;
        directeur?: T;
        email?: T;
        telephone?: T;
        site?: T;
      };
  hebergeur?:
    | T
    | {
        nom?: T;
        adresse?: T;
        telephone?: T;
        site?: T;
      };
  mediateur?:
    | T
    | {
        nom?: T;
        site?: T;
      };
  dpoEmail?: T;
  developpeur?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  twitch?:
    | T
    | {
        channelLogin?: T;
        clientId?: T;
        clientSecret?: T;
        oauthEnabled?: T;
      };
  youtube?:
    | T
    | {
        channelId?: T;
        vodChannelHandle?: T;
      };
  stripe?:
    | T
    | {
        test?:
          | T
          | {
              publishableKey?: T;
              secretKey?: T;
              webhookSecret?: T;
            };
        live?:
          | T
          | {
              publishableKey?: T;
              secretKey?: T;
              webhookSecret?: T;
            };
      };
  paypal?:
    | T
    | {
        sandbox?:
          | T
          | {
              clientId?: T;
              clientSecret?: T;
              webhookId?: T;
            };
        live?:
          | T
          | {
              clientId?: T;
              clientSecret?: T;
              webhookId?: T;
            };
      };
  gelato?:
    | T
    | {
        apiKey?: T;
        webhookToken?: T;
      };
  smtp?:
    | T
    | {
        host?: T;
        port?: T;
        secure?: T;
        user?: T;
        password?: T;
        from?: T;
        adminNotify?: T;
      };
  discord?:
    | T
    | {
        scheduleWebhookUrl?: T;
      };
  analytics?:
    | T
    | {
        provider?: T;
        scriptUrl?: T;
        siteId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}